### PR TITLE
chore(dependencies): require Python >= 3.8 and Django >= 4.1 

### PR DESCRIPTION
**Pull request by glarrain-cdd**
## Why

Several Python and Django packages on which this project depends cannot be upgraded because they require newer versions of Python and Django, e.g. 'django-cors-headers'.

Since this is a library, not an app, those outdated dependencies conflict with the different versions used in the app that uses this library.

Also, the Python and Django versions for which support was removed, are no longer officially supported by their maintainers, thus become security liabilities.

### Main

This change removes support for:

- Python 3.6 (no longer maintained)
- Python 3.7 (no longer maintained)
- Django 4.0 (no longer maintained)

And adds explicit support for:

- Django 4.1
- Django 4.2

References:

- [Django releases](https://www.djangoproject.com/download/#supported-versions)
- [Python releases](https://devguide.python.org/versions/#status-of-python-versions)

### Secondary

- 'django-cors-headers': upgrade to `>=3.14, <4.0` ([ref](https://github.com/adamchainz/django-cors-headers/blob/main/CHANGELOG.rst#3140-2023-02-25))
- 'coverage': upgrade to `>=6.0.2` ([ref](https://github.com/nedbat/coveragepy/blob/master/CHANGES.rst#version-602--2021-10-11))
- 'marshmallow': update to `>=3.15, <3.16` ([ref](https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#3150-2022-03-12))

### General

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [x] Test manually the implemented changes
- [x] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [x] Consider the security impact of the changes made

### CODE REVIEW

**Comment by jbarreau** [comment]
Hi @glarrain-cdd, 
Thank you for the pull request, we have discussions about the removal of versions that are no longer supported because we may have customer using them, in our policy we still support theses old versions.
We will do analysis to see which versions of python and django our customers uses, and so which version support we can remove.

I keep you in touch when I have informations to share about this subject.

Best regards.

**Comment by ghusse** [comment]
I think that the main reason behind this PR is more to support newer versions that unsupport old ones. Am I right @glarrain-cdd 

Is it possible to add support of new versions without losing the compatibility with the older ones?

**Comment by jbarreau** [comment]
Hi @glarrain-cdd,
After looking at our customers django versions, that is impossible for us to drop support for any versions of python or django. 
Mainly because django 3.2 is still compatible with python 3.6 and 3.7. 

So the solution proposed by @ghusse seams to be the good one.

For this PR, can you : 

- remove the versions dropping for django and python,
- change the title of the PR, and replacing 'chore' by 'feat' : for new support, we prefer that semantic release make a new minor version.

I still am looking for the coverage error in the CI.

**Comment by glarrain-cdd** [comment]
Sorry, this PR was created in a rush. I'll fix it later.

The context was that I was trying to make it work with the latest releases of Python and Django.

Thanks

**Comment by jbarreau** [comment]
Hi @glarrain-cdd,
Because you close this pull request, I opened an issue in our product board, I'll come back to you when it's done.

Best regards.

**Pull request closed without merging**
